### ISSUE TITLE
coffeescript-eclipse Future

### ISSUE THREAD

**Issue by paulvi** [adamschmideg/coffeescript-eclipse#13]
Hi Adam

coffeescript-eclipse is still for a year. Would you bless the project to go on within [Nodeclipse](https://github.com/Nodeclipse/coffeescript-eclipse)?

**Comment by adamschmideg** [comment]
my blessings :)

**Comment by paulvi** [comment]
Adam, could please keep this issue open.
It is top issue in the list. So people are likely look in.

UPDATE： Though now with updated readme, it is OK
